### ISSUE TITLE
Error when attempting to run playbook

### ISSUE THREAD

**Issue by DonSchenck** [snowdrop/istio-integration#3]
I get

`dschenck-OSX:istio-integration dschenck$ ansible-playbook ansible/main.yml -t create-vm --ask-become-pass`
SUDO password: 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/dschenck/istio-integration/ansible/main.yml': line 15, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - import_tasks: minishift/delete.yml
      ^ here

The error appears to have been in '/Users/dschenck/istio-integration/ansible/main.yml': line 15, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - import_tasks: minishift/delete.yml
      ^ here

**Comment by cmoulliard** [comment]
Which ansible version do you use @DonSchenck ?

**Comment by geoand** [comment]
@DonSchenck I got this same error when I accidentally executed the playbook with Ansible 2.0. When I tried Ansible 2.4 the playbook was run as expected

**Comment by cmoulliard** [comment]
README mentions that Ansible 2.4 is required.
